apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: {{ .Values.railsapp.replicaCount }}
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
      - name: rails-app
        image: "{{ .Values.railsapp.image.repository }}:{{ .Values.railsapp.image.tag }}"
        imagePullPolicy: {{ .Values.railsapp.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.railsapp.containerPort }}
          protocol: TCP
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.databaseUrlSecretName }}
              key: url
        - name: CONTENT_API_URL
          value: {{ .Values.contentapiurl }}
