#!/bin/sh -e
NAMESPACE=$1
DYNAMIC_HOSTNAME=$2

# These variables are required in multiple places such as
# tag_and_push_docker_image as well as the bin/<NAMESPACE>_deploy.sh scripts
export safe_git_branch=${CIRCLE_BRANCH//\//-}
export short_sha="$(git rev-parse --short=7 $CIRCLE_SHA1)"
export IMAGE_TAG="$safe_git_branch.$short_sha"

export CLEANED_BRANCH_NAME=$(echo $CIRCLE_BRANCH | sed 's/^feature[-/]//' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-28 | sed 's/-$//')
if [ $DYNAMIC_HOSTNAME = true ]; then
  export RELEASE_NAME=${CLEANED_BRANCH_NAME}
  export RELEASE_HOST=${RELEASE_NAME}-${HOST}
else
  export RELEASE_NAME=cla-frontend
  export RELEASE_HOST=${HOST}
fi
