#!/bin/sh -e

source $(dirname "$0")/define_build_environment_variables
built_tag="$1"
repository="$2"

case $repository in
  app)
      docker_repository="${ECR_URL_APP}"
      ;;
  socket-server)
      docker_repository="${ECR_URL_SOCKET_SERVER}"
      ;;
esac

export CLEANED_BRANCH_NAME=$(echo $CIRCLE_BRANCH | sed 's/^feature[-/]//' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-28 | sed 's/-$//')
function tag_and_push() {
  tag="$1"
  echo
  echo "Tagging and pushing $tag..."
  docker tag $built_tag $tag
  docker push $tag
}

tag_and_push "$docker_repository:$safe_git_branch.$short_sha"
tag_and_push "$docker_repository:$safe_git_branch"

if [ "$CIRCLE_BRANCH" == "master" ]; then
  tag_and_push "$docker_repository:latest"
fi
