"""empty message

Revision ID: 1790888413bd
Revises: 78ad56fb9920
Create Date: 2022-04-12 12:55:08.550669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1790888413bd'
down_revision = '78ad56fb9920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'email',
               existing_type=sa.VARCHAR(length=180),
               nullable=True)
    op.drop_constraint('application_email_key', 'application', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('application_email_key', 'application', ['email'])
    op.alter_column('application', 'email',
               existing_type=sa.VARCHAR(length=180),
               nullable=False)
    # ### end Alembic commands ###
