"""empty message

Revision ID: 1dc1d1539e97
Revises: 200437298859
Create Date: 2022-06-23 17:19:37.716914

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1dc1d1539e97'
down_revision = '200437298859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('how_easy_to_complete_application', sa.String(length=20), nullable=True),
    sa.Column('any_questions_difficult_to_answer', sa.String(length=3), nullable=True),
    sa.Column('which_questions_difficult_to_answer', sa.String(length=5000), nullable=True),
    sa.Column('needed_to_call_admin_team', sa.String(length=3), nullable=True),
    sa.Column('what_did_you_need_help_with', sa.String(length=5000), nullable=True),
    sa.Column('used_doc_checker', sa.String(length=11), nullable=True),
    sa.Column('experience_of_using_doc_checker', sa.String(length=5000), nullable=True),
    sa.Column('any_other_suggestions', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
