"""empty message

Revision ID: 200437298859
Revises: a16560e9e082
Create Date: 2022-05-23 09:52:40.887257

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '200437298859'
down_revision = 'a16560e9e082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('filesCreated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'filesCreated')
    # ### end Alembic commands ###
