"""empty message

Revision ID: 2eca8ff1d7bb
Revises: f1927d10ecfc
Create Date: 2022-05-10 09:27:15.071655

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2eca8ff1d7bb'
down_revision = 'f1927d10ecfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'reference_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('application_reference_number_key', 'application', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('application_reference_number_key', 'application', ['reference_number'])
    op.alter_column('application', 'reference_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
