"""empty message

Revision ID: 357c453dd58d
Revises: 2eca8ff1d7bb
Create Date: 2022-05-10 09:32:08.182668

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '357c453dd58d'
down_revision = '2eca8ff1d7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'reference_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=50),
               existing_nullable=True)
    op.alter_column('application', 'email',
               existing_type=sa.VARCHAR(length=180),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'email',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=500),
               type_=sa.VARCHAR(length=180),
               existing_nullable=True)
    op.alter_column('application', 'reference_number',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
