"""empty message

Revision ID: 5f57f0270e70
Revises: 1a4ee52a6966
Create Date: 2022-03-10 11:41:34.320522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f57f0270e70'
down_revision = '1a4ee52a6966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('passwordResetRequired', sa.Boolean(), nullable=True),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_user')
    # ### end Alembic commands ###
