"""empty message

Revision ID: 98b9a347a455
Revises: bcf8946cf060
Create Date: 2022-03-21 12:32:38.931523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b9a347a455'
down_revision = 'bcf8946cf060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('downloaded', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('downloadedBy', sa.String(length=180), nullable=True))
    op.add_column('application', sa.Column('completed', sa.DateTime(), nullable=True))
    op.add_column('application', sa.Column('completedBy', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'completedBy')
    op.drop_column('application', 'completed')
    op.drop_column('application', 'downloadedBy')
    op.drop_column('application', 'downloaded')
    # ### end Alembic commands ###
