"""empty message

Revision ID: a16560e9e082
Revises: e4c7dcc8c1c0
Create Date: 2022-05-16 12:56:14.374375

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'a16560e9e082'
down_revision = 'e4c7dcc8c1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'email',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('security_code', 'code',
               existing_type=sa.VARCHAR(length=5),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=50),
               existing_nullable=False)
    op.alter_column('security_code', 'email',
               existing_type=sa.VARCHAR(length=180),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_code', 'email',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=500),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    op.alter_column('security_code', 'code',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=50),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('application', 'email',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###
