"""empty message

Revision ID: b017e9c6b31d
Revises: 5f57f0270e70
Create Date: 2022-03-15 10:51:29.453725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b017e9c6b31d'
down_revision = '5f57f0270e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('userType', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'userType')
    # ### end Alembic commands ###
