"""empty message

Revision ID: bcf8946cf060
Revises: b017e9c6b31d
Create Date: 2022-03-16 10:37:48.326692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf8946cf060'
down_revision = 'b017e9c6b31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('dateLastLogin', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'dateLastLogin')
    # ### end Alembic commands ###
