"""empty message

Revision ID: e4c7dcc8c1c0
Revises: 357c453dd58d
Create Date: 2022-05-16 12:42:20.680941

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'e4c7dcc8c1c0'
down_revision = '357c453dd58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'reference_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'application', ['reference_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='unique')
    op.alter_column('application', 'reference_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
