"""empty message

Revision ID: f1927d10ecfc
Revises: 1790888413bd
Create Date: 2022-05-10 09:22:40.633446

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1927d10ecfc'
down_revision = '1790888413bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'reference_number',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('application', 'user_input',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=50000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'user_input',
               existing_type=sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(length=50000),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('application', 'reference_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
