name: 'Deploy (sandbox)'

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}  # Prevents more than one instance of this workflow running at the same time

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-shared.yml
    with:
      cf_space: 'sandbox'
      app_name_public: 'geo-gender-recognition-certificate'
      app_name_admin: 'geo-gender-recognition-certificate-admin'
      app_name_dashboard: 'geo-gender-recognition-certificate-dashboard'
      app_name_iprestrict_admin: 'grc-sandbox-iprestrict-admin'
      manifest_name: 'sandbox'
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      allowed_ips_admin: ${{ secrets.ALLOWED_IPS_ADMIN_SANDBOX }}
